on: [push, pull_request]

name: Run tests

jobs:
  all:
    name: Run tests
    timeout-minutes: 30
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:prod